---
- platform: history_stats
  name: battery_bike_charged_today
  entity_id: binary_sensor.bike_battery
  state: "on"
  type: count
  start: "{{ now().replace(hour=10, minute=0, second=0) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: battery_bike_changed_last_48h
  entity_id: binary_sensor.bike_battery
  state: "on"
  type: count
  duration:
    hours: 48
  end: "{{ now() }}"
