---
- platform: min_max
  name: temperature_bedroom_roof
  type: mean
  entity_ids:
    - sensor.x_multi_bedroom_roof_bed_temperature
    - sensor.x_multi_bedroom_roof_temperature

- platform: min_max
  name: temperature_roof
  type: mean
  entity_ids:
    - sensor.temperature_bedroom_roof
    - sensor.x_multi_mezzanine_temperature

- platform: min_max
  name: temperature_livingroom
  type: mean
  entity_ids:
    - sensor.x_multi_livingroom_fireplace_temperature
    - sensor.x_multi_livingroom_sofa_temperature

- platform: min_max
  name: temperature_kitchen
  type: mean
  entity_ids:
    - sensor.x_multi_kitchen_floor_temperature
    - sensor.x_multi_kitchen_temperature

- platform: min_max
  name: temperature_bedroom_girls
  type: mean
  entity_ids:
    - sensor.x_multi_mina_clara_bedroom_win_temperature
    - sensor.x_multi_mina_clara_bedroom_bed_temperature

- platform: min_max
  name: temperature_office_melanie
  type: mean
  entity_ids:
    - sensor.x_multi_bedroom_ground_floor_win_temperature
    - sensor.x_multi_bedroom_ground_floor_temperature
