- platform: template
  sensors:
    temperature_target_preset_bathrooms:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_bathrooms', 'on') %}
          {{ states('input_number.temperature_comfort_preset_bathrooms') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_bathrooms') }}
        {% endif %}
      <<: &common_options
        attribute_templates:
          comfort_mode: "{{states('input_boolean.temperature_comfort_preset_bathrooms')}}"
          holiday_mode: "{{states('input_boolean.vacation_mode')}}"
        unit_of_measurement: °C
    temperature_target_preset_bedrooms:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_bedrooms', 'on') %}
          {{ states('input_number.temperature_comfort_preset_bedrooms') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_bedrooms') }}
        {% endif %}
      <<: *common_options
    temperature_target_preset_common_rooms:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_common_rooms', 'on') %}
          {{ states('input_number.temperature_comfort_preset_common_rooms') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_common_rooms') }}
        {% endif %}
      <<: *common_options
    temperature_target_preset_bedrooms_kids:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_bedrooms_kids', 'on') %}
          {{ states('input_number.temperature_comfort_preset_bedrooms_kids') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_bedrooms_kids') }}
        {% endif %}
      <<: *common_options
    temperature_target_preset_clement_office:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_clement_office', 'on') %}
          {{ states('input_number.temperature_comfort_preset_clement_office') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_clement_office') }}
        {% endif %}
      <<: *common_options
    temperature_target_preset_melanie_office:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_melanie_office', 'on') %}
          {{ states('input_number.temperature_comfort_preset_melanie_office') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_melanie_office') }}
        {% endif %}
      <<: *common_options
    temperature_target_preset_floor:
      value_template: >-
        {% if is_state('input_boolean.vacation_mode', 'on') %}
          {{ states('input_number.temperature_frost_free') }}
        {% elif is_state('input_boolean.temperature_comfort_preset_floor', 'on') %}
          {{ states('input_number.temperature_comfort_preset_floor') }}
        {% else %}
          {{ states('input_number.temperature_reduced_preset_floor') }}
        {% endif %}
      <<: *common_options
