alias: add_task_washing_machine_full
description: Add Todoist task when the washing machine is full
id: a4b5050d-2d4e-4f03-b153-a879c862194e

trigger:
  - platform: state
    entity_id: input_boolean.washing_machine_full
    to: "on"
action:
  service: todoist.new_task
  data:
    content: 🧺 Sortir le linge de la machine à laver
    due_date_string: Aujourd'hui
    due_date_lang: fr
