---
alias: turn_on_washing_machine_full
description: Turn on Washing machine full when finished to run
id: 11a9f05c-df21-495b-aa15-bfab293669a4
trigger:
  platform: state
  entity_id: binary_sensor.washing_machine
  to: "off"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.washing_machine_full
  - service_template: >-
      {% if not is_state('person.clement_patout', 'home') and is_state('person.melanie_patout', 'home') %}
        notify.telegram_melanie
      {% elif is_state('person.clement_patout', 'home') and not is_state('person.melanie_patout', 'home') %}
        notify.telegram_clement
      {% else %}
        notify.telegram
      {% endif %}
    data:
      title: "\U0001F455 **Machine à laver**"
      message: >
        Il semblerait que la machine à laver a terminé
