---
description: Turn off heating when window is open
alias: bedroom_girls_turn_off_heating_window
id: 2d714926-336f-44ec-9447-d699509aa68d
trigger:
  platform: state
  entity_id: binary_sensor.open_bedroom
  to: "on"
action:
  - service: climate.turn_off
    data:
      entity_id: climate.chambre_1er