alias: turn_scene_off_when_webcam_off
description: Turn off live scene when the webcam is off
id: fc579aed-f8d1-4061-b667-0cc6d0290df2

trigger:
  - platform: state
    entity_id: 
      - binary_sensor.macbook_pro_2_hd_web_camera_camera
      - binary_sensor.macbook_pro_2_hd_web_camera_2
      - binary_sensor.macbook_pro_2_cam_link_4k_camera
      - binary_sensor.macbook_pro_2_cam_link_4k_2
      - binary_sensor.macbook_pro_2_cam_link_4k_camera_2
    from: "on"
    to: "off"
action:
  service: scene.turn_on
  entity_id: scene.office_backup
