---
description: Turn on heating when windows are closed
alias: cellar_room_turn_on_heating_window
id: 20b985bc-6eb9-492b-8d6d-ccbf3243eb3b
trigger:
  platform: state
  entity_id: binary_sensor.open_cellar_room
  to: "off"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.chambre_cave
