---
description: Turn Off Heating when windows are open
alias: cellar_room_turn_off_heating_window
id: 60701fb9-cf1e-4f26-8304-dc7f0d8855c7
trigger:
  platform: state
  entity_id: binary_sensor.open_cellar_room
  to: "on"
action:
  - service: climate.turn_off
    data:
      entity_id: climate.chambre_cave
