---
# This handles the loading of my automations
#
# https://www.home-assistant.io/docs/automation/
# The ID in my automation is to be able to edit the automation in the UI editor
automation: !include ../automations.yaml
automation split: !include_dir_list ../automations
