- platform: generic_thermostat
  name: Salon
  heater: switch.chauffage_salon
  target_sensor: sensor.temperature_livingroom

- platform: generic_thermostat
  name: Cuisine
  heater: switch.chauffage_cuisine
  target_sensor: sensor.temperature_kitchen

- platform: generic_thermostat
  name: Chambre RDC
  heater: switch.chauffage_chambre_rdc
  target_sensor: sensor.temperature_office_melanie

- platform: generic_thermostat
  name: Escalier
  heater: group.heating_stairs
  target_sensor: sensor.x_multi_stairs_first_floor_temperature

- platform: generic_thermostat
  name: Chambre 1er
  heater: switch.chauffage_chambre_1er
  target_sensor: sensor.temperature_bedroom_girls

- platform: generic_thermostat
  name: Salle de bain
  heater: switch.chauffage_salle_de_bain
  target_sensor: sensor.x_multi_bathroom_temperature

- platform: generic_thermostat
  name: Chambre Florian
  heater: switch.chauffage_chambre_florian
  target_sensor: sensor.x_multi_florian_bedroom_temperature

- platform: generic_thermostat
  name: Chambre Toit
  heater: switch.chauffage_chambre_toit
  target_sensor: sensor.temperature_bedroom_roof

- platform: generic_thermostat
  name: Chambre Cave
  heater: switch.chauffage_chambre_cave
  target_sensor: sensor.x_multi_bedroom_cellar_temperature

- platform: generic_thermostat
  name: Buanderie
  heater: switch.chauffage_buanderie
  target_sensor: sensor.x_multi_laundryroom_temperature

- platform: generic_thermostat
  name: Mezzanine
  heater: switch.chauffage_mezzanine
  target_sensor: sensor.x_multi_mezzanine_temperature

- platform: generic_thermostat
  name: Entrée
  heater: switch.chauffage_entree
  target_sensor: sensor.x_multi_entrance_temperature
