# This is the starting point of the configuration
homeassistant:
  whitelist_external_dirs:
    - /tmp
  # All Integrations:
  packages: !include_dir_named integrations
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

scene: !include scenes.yaml
climate: !include climate.yaml
sensor: !include_dir_merge_list sensors
