---
description: Turn Off Pause CD in livingroom
alias: livingroom_cd_audio_turn_off
id: 83e1f392-b5c8-4e18-8d4f-49dc242b54b5

trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_control
    event: 1001
condition:
  condition: template
  value_template: >-
    {{ is_state_attr('remote.harmony_hub', 'current_activity', 'CD audio') }}
action:
  service: remote.turn_off
  entity_id: remote.harmony_hub
