---
description: Turn On CD in livingroom
alias: livingroom_cd_audio_turn_on
id: 899fc3ba-26d6-4582-86ec-cba5d39d632d

trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_control
    event: 1002
condition:
  condition: state
  entity_id: remote.harmony_hub
  state:  'off'
action:
  - service: script.start_audio_disc