---
description: Switch off TV scene on pausing tv
alias: livingroom_pause_tv_night_lights
id: 185c6d65-9028-4cd7-b48c-add371ff4930
trigger:
  platform: state
  entity_id: binary_sensor.playing_on_tv
  to: "off"
  for:
    seconds: 5
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: sun.sun
      state: below_horizon
    - condition: time
      after: "20:00:00"
action:
  service: scene.turn_on
  entity_id: scene.light_cozy_livingroom
