---
description: Turn on the heating if a window get closed
alias: livingroom_heating_window_closed
id: bf430a26-1a3f-42d9-b9ef-dd8c4419d75a
trigger:
  platform: state
  entity_id: binary_sensor.open_livingroom
  to: "off"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.salon
