---
description: Turn off the heating if a window is open
alias: living_room_heating_window_open
id: fe35eec8-52b4-4740-93e1-426f6eb18b98
trigger:
  platform: state
  entity_id: binary_sensor.open_livingroom
  to: "on"
action:
  - service: climate.turn_off
    data:
      entity_id: climate.salon
