---
description: Turn Off HDMI hyperion when switch off harmony
id: 9229f64e-2437-4439-b7cd-f6dc683e1dd4
alias: turn_off_hdmi_hyperion_harmony_off
trigger:
  - platform: state
    entity_id: remote.harmony_hub
    to:  'off'
action:
    - service: switch.turn_off
      entity_id: switch.hdmi_hyperion