---
alias: set_heating_all_sleeping
id: d73c4055-ba14-477d-893a-a4dd45515523
description: Shuting all down when everyone is in bed
trigger:
  platform: state
  entity_id: input_boolean.sleeping_mode
  to: "on"
action:
  service: input_boolean.turn_off
  data:
    entity_id:
      - temperature_high_bathroom
      - temperature_high_bedroom_cellar
      - temperature_high_florian_bedroom
      - temperature_high_bedroom_girls
      - temperature_high_office_melanie
      - temperature_high_bedroom_roof
      - temperature_high_entrance
      - temperature_high_kitchen
      - temperature_high_laundryroom
      - temperature_high_livingroom
      - temperature_high_mezzanine
      - temperature_high_stairs
