- platform: integration
  source: sensor.heating_livingroom_power
  name: heating_livingroom_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_kitchen_power
  name: heating_kitchen_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bathroom_power
  name: heating_bathroom_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bedroom_cellar_power
  name: heating_bedroom_cellar_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bedroom_ground_floor_power
  name: heating_bedroom_ground_floor_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bedroom_mina_clara_power
  name: heating_bedroom_mina_clara_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bedroom_florian_power
  name: heating_bedroom_florian_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_bedroom_roof_power
  name: heating_bedroom_roof_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_entrance_power
  name: heating_entrance_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_mezzanine_power
  name: heating_mezzanine_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_stairs_cellar_power
  name: heating_stairs_cellar_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_stairs_ground_floor_power
  name: heating_stairs_ground_floor_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_stairs_first_floor_power
  name: heating_stairs_first_floor_consumption
  round: 2
  unit_prefix: k
- platform: integration
  source: sensor.heating_laundryroom_power
  name: heating_laundryroom_consumption
  round: 2
  unit_prefix: k