---
description: Turn Off Heating when windows is open
alias: bathroom_turn_off_heating_window
id: 74c8d918-3549-41ea-b9cc-d184d717cb93

trigger:
  platform: state
  entity_id: binary_sensor.open_bathroom
  to: "on"

  action:
  - service: climate.turn_off
    data:
      entity_id: climate.salle_de_bain