---
description: Turn On Heating when windows is closed
alias: bathroom_turn_on_heating_window
id: 1a674a55-4983-45e5-a94f-9acf1b1aa59d
trigger:
  platform: state
  entity_id: binary_sensor.open_bathroom
  to: "off"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.salle_de_bain