---
description: Turn On Heating when windows is closed
alias: bedroom_ground_floor_turn_on_heating_window
id: 1aa76979-e08a-445e-8596-a910f2b60fcc
trigger:
  platform: state
  entity_id: binary_sensor.x_window_bedroom_ground_floor
  to: "off"
action:
  - service: climate.turn_on
    data:
      entity_id: climate.chambre_rdc