---
description: Open the gate when clicking on right switch in kitchen
alias: kitchen_open_gate_switch
id: c5a6ef79-c4df-4be0-891b-48318e3b0131
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: transmitter_2_gang
    event: 2002
action:
  service: script.open_gate

