---
description: "Alert when motion or door or window if we sleep"
id: 439845b5-b893-495a-ae27-765f79fe6360
alias: "alert_alarm_night"

trigger:
  - platform: state
    to: "on"
    entity_id: binary_sensor.motion_ground_floor
  - platform: state
    to: "on"
    entity_id: binary_sensor.open_ground_floor

condition:
  - condition: state
    entity_id: input_boolean.sleeping_mode
    state: "true"
action:
  - service: notify.telegram
    data_template:
      title: "\U0001f6a8 *Alerte présence.*"
      message: >
        Nous avons détectés des signes de présences anormales.

        Fenêtres/Portes ouvertes:
        {%for s in states.binary_sensor if s.entity_id.startswith('binary_sensor.open_') and s.state == 'on' %}{{s.name}}{%if not loop.last%},{%endif%}{%endfor%}

        Détection de mouvements:
        {%for s in states.binary_sensor if s.entity_id.startswith('binary_sensor.motion_') and s.state == 'on' %}{{s.name}}{%if not loop.last%},{%endif%}{%endfor%}

  - service: notify.all_ios
    data:
      title: "\U0001f6a8 *Alerte présence.*"
      message: >
        Nous avons détectés des signes de présences anormales.

        Fenêtres/Portes ouvertes:
        {%for s in states.binary_sensor if s.entity_id.startswith('binary_sensor.open_') and s.state == 'on' %}{{s.name}}{%if not loop.last%},{%endif%}{%endfor%}

        Détection de mouvements:
        {%for s in states.binary_sensor if s.entity_id.startswith('binary_sensor.motion_') and s.state == 'on' %}{{s.name}}{%if not loop.last%},{%endif%}{%endfor%}:
      data:
        push:
          sound:
            name: "default"

            critical: 1
            volume: 1.0
