---
# For the moment will use one heating availibility
description: Send telegram when doorbell die
alias: notify_doorbell_dead
id: ff367d5c-a5f7-4108-8787-f978107ec77d
trigger:
  platform: state
  entity_id: switch.chaufface_cuisine
  to: unavailable
action:
  service: notify.telegram_clement
  data:
    title: "\000026680000FR0F *Chauffage En Vie*"
    message: "Le chauffage fonctionne !!! \0001f973"