---
description: Turn on light in cellar entrance when motion detected
alias: cellar_entrance_turn_on_light_motion
id: bb537934-9cb6-4ab0-b76c-420505c529fe
trigger:
  platform: state
  entity_id: binary_sensor.motion_cellar_entrance
  from: "off"
  to: "on"
action:
  service: light.turn_on
  entity_id: light.cellar_entrance
